steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/grand-ward-502705-m1/incident-management-repo/incident-management-ui",
        "."
      ]

  # Push image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/grand-ward-502705-m1/incident-management-repo/incident-management-ui"
      ]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "incident-management-ui",
        "--image",
        "asia-south1-docker.pkg.dev/grand-ward-502705-m1/incident-management-repo/incident-management-ui",
        "--region",
        "asia-south1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080"
      ]

images:
  - "asia-south1-docker.pkg.dev/grand-ward-502705-m1/incident-management-repo/incident-management-ui"

options:
  logging: CLOUD_LOGGING_ONLY
